add esr_el3 register
rust-embedded/aarch64-cpu pull request #10
Opened 2023-02-24 04:53 UTC by rmsyn

2023-07-18 20:23 UTC, nchong-at-aws requested changes

2023-07-18 20:23 UTC, nchong-at-aws commented on src/registers/esr_el3.rs
> +        /// Instruction Specific Syndrom 2
```suggestion
        /// Instruction Specific Syndrome 2
```

2023-07-18 20:23 UTC, nchong-at-aws commented on src/registers/esr_el3.rs
> +        ISS2 OFFSET(36) NUMBITS(5) [],
Offset should be 32

![Screenshot 2023-07-18 at 4 13 21 PM](https://github.com/rust-embedded/aarch64-cpu/assets/52972368/3a8386ba-0c35-482c-b362-d315921e9b7a)

2023-07-18 20:23 UTC, nchong-at-aws commented on src/registers/esr_el3.rs
> +        EC  OFFSET(26) NUMBITS(6) [
.

2023-07-20 04:54 UTC, rmsyn commented on src/registers/esr_el3.rs
> +        EC  OFFSET(26) NUMBITS(6) [
?

2023-07-20 16:34 UTC, nchong-at-aws approved these changes

2023-07-20 16:35 UTC, merged